//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Web.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCuentaPago
    {
        public int IdCuentaPago { get; set; }
        public int Consecutivo { get; set; }
        public int IdMetodoPago { get; set; }
        public string IdentificadorCuenta { get; set; }
        public string UltimosCuatroDigitos { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Predeterminado { get; set; }
    
        public virtual tMetodoPago tMetodoPago { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
