//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Web.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTransaccionPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTransaccionPago()
        {
            this.tReciboPago = new HashSet<tReciboPago>();
        }
    
        public int IdTransaccion { get; set; }
        public int Consecutivo { get; set; }
        public int IdMaestro { get; set; }
        public int IdMetodoPago { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoPago { get; set; }
        public string CodigoTransaccion { get; set; }
        public decimal Impuesto { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual tMaestro tMaestro { get; set; }
        public virtual tMetodoPago tMetodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReciboPago> tReciboPago { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
